# version: "3.9"

# services:
#   db:
#     image: postgres:16
#     container_name: fintech-db
#     environment:
#       POSTGRES_DB: fintech
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: root
#     ports:
#       - "5432:5432"
#     volumes:
#       - db_data:/var/lib/postgresql/data

#   backend:
#     build: ./backend
#     container_name: fintech-backend
#     ports:
#       - "9099:9099"
#     depends_on:
#       - db
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/FinTech
#       SPRING_DATASOURCE_USERNAME: postgres
#       SPRING_DATASOURCE_PASSWORD: root
#     restart: always

#   frontend:
#     build: ./frontend
#     container_name: fintech-frontend
#     ports:
#       - "3000:80"
#     depends_on:
#       - backend
#     restart: always

# volumes:
#   db_data:
