# version: "3.9"

# services:
#   postgres:
#     image: postgres:15
#     container_name: postgres-db
#     environment:
#       POSTGRES_DB: FinTech
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: root
#     ports:
#       - "5432:5432"

#   backend:
#     build: ./Backend/FinTech-Digital-Banking
#     container_name: springboot-backend
#     depends_on:
#       - postgres
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/FinTech

#       SPRING_DATASOURCE_USERNAME: postgres
#       SPRING_DATASOURCE_PASSWORD: root
#       SPRING_MAIL_USERNAME: your_email@gmail.com
#       SPRING_MAIL_PASSWORD: your_app_password
#       TRANSFER_OTP_THRESHOLD: 10000
#     ports:
#       - "9099:9099"

#   frontend:
#     build: ./frontend
#     container_name: react-frontend
#     depends_on:
#       - backend
#     environment:
#      REACT_APP_BACKEND_URL: http://springboot-backend:9099
#     ports:
#       - "3000:80"








services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: FinTech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./Backend/FinTech-Digital-Banking
    container_name: springboot-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/FinTech
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_MAIL_USERNAME: gangadharirushitha@gmail.com
      SPRING_MAIL_PASSWORD: rqqmgnateouwswuo
      TRANSFER_OTP_THRESHOLD: 10000
    ports:
      - "9099:9099"

  frontend:
    build: ./frontend
    container_name: react-frontend
    depends_on:
      - backend
    environment:
      REACT_APP_BACKEND_URL: http://springboot-backend:9099
    ports:
      - "3000:80"

volumes:
  postgres_data:
